
//
// ios-swift/enum-default-default-light.swift
//

// Do not edit directly
// Generated on Tue, 13 Feb 2024 05:41:54 GMT


import UIKit

public enum  {
    public static let ocBase2 = 2
    public static let ocBase4 = 4
    public static let ocBase8 = 8
    public static let ocBorderAction = UIColor(red: 0.031, green: 0.486, blue: 0.263, alpha: 1)
    public static let ocBorderActionHover = UIColor(red: 0.031, green: 0.486, blue: 0.263, alpha: 1)
    public static let ocBorderDisabled = UIColor(red: 0.439, green: 0.439, blue: 0.439, alpha: 1)
    public static let ocBorderError = UIColor(red: 0.761, green: 0.129, blue: 0.059, alpha: 1)
    public static let ocBorderFocus = UIColor(red: 0.031, green: 0.486, blue: 0.263, alpha: 1)
    public static let ocBorderHighlight = UIColor(red: 0.133, green: 0.573, blue: 0.643, alpha: 1)
    public static let ocBorderInformation = UIColor(red: 0.000, green: 0.396, blue: 1.000, alpha: 1)
    public static let ocBorderPrimary = UIColor(red: 0.831, green: 0.831, blue: 0.831, alpha: 1)
    public static let ocBorderSecondary = UIColor(red: 0.031, green: 0.486, blue: 0.263, alpha: 1)
    public static let ocBorderSuccess = UIColor(red: 0.031, green: 0.486, blue: 0.263, alpha: 1)
    public static let ocBorderWarning = UIColor(red: 0.918, green: 0.690, blue: 0.063, alpha: 1)
    public static let ocBorderWidth05 = 0.5
    public static let ocBorderWidth1 = 1
    public static let ocBorderWidth15 = 1.5
    public static let ocBorderWidth2 = 2
    public static let ocBorderWidth25 = 2.5
    public static let ocBorderWidth3 = 3
    public static let ocBorderWidth4 = 4
    public static let ocBorderWidth5 = 5
    public static let ocBorderWidthNone = 0
    public static let ocColorAccentDark = UIColor(red: 0.133, green: 0.573, blue: 0.643, alpha: 1)
    public static let ocColorAccentDarker = UIColor(red: 0.133, green: 0.573, blue: 0.643, alpha: 1)
    public static let ocColorAccentDefault = UIColor(red: 0.133, green: 0.573, blue: 0.643, alpha: 1)
    public static let ocColorAccentLight = UIColor(red: 0.133, green: 0.573, blue: 0.643, alpha: 1)
    public static let ocColorAccentLighter = UIColor(red: 0.133, green: 0.573, blue: 0.643, alpha: 1)
    public static let ocColorAccentLightest = UIColor(red: 0.133, green: 0.573, blue: 0.643, alpha: 1)
    public static let ocColorBlackBlack = UIColor(red: 0.067, green: 0.067, blue: 0.067, alpha: 1)
    public static let ocColorBlue100 = UIColor(red: 0.000, green: 0.396, blue: 1.000, alpha: 1)
    public static let ocColorBlue200 = UIColor(red: 0.000, green: 0.396, blue: 1.000, alpha: 1)
    public static let ocColorBlue300 = UIColor(red: 0.000, green: 0.396, blue: 1.000, alpha: 1)
    public static let ocColorBlue400 = UIColor(red: 0.000, green: 0.396, blue: 1.000, alpha: 1)
    public static let ocColorBlue500 = UIColor(red: 0.000, green: 0.396, blue: 1.000, alpha: 1)
    public static let ocColorBlue600 = UIColor(red: 0.000, green: 0.396, blue: 1.000, alpha: 1)
    public static let ocColorBlue700 = UIColor(red: 0.000, green: 0.396, blue: 1.000, alpha: 1)
    public static let ocColorBlue800 = UIColor(red: 0.000, green: 0.396, blue: 1.000, alpha: 1)
    public static let ocColorBlue900 = UIColor(red: 0.000, green: 0.396, blue: 1.000, alpha: 1)
    public static let ocColorErrorDark = UIColor(red: 0.761, green: 0.129, blue: 0.059, alpha: 1)
    public static let ocColorErrorDarker = UIColor(red: 0.761, green: 0.129, blue: 0.059, alpha: 1)
    public static let ocColorErrorDefault = UIColor(red: 0.761, green: 0.129, blue: 0.059, alpha: 1)
    public static let ocColorErrorLight = UIColor(red: 0.761, green: 0.129, blue: 0.059, alpha: 1)
    public static let ocColorErrorLighter = UIColor(red: 0.761, green: 0.129, blue: 0.059, alpha: 1)
    public static let ocColorErrorLightest = UIColor(red: 0.761, green: 0.129, blue: 0.059, alpha: 1)
    public static let ocColorGray10 = UIColor(red: 0.945, green: 0.945, blue: 0.945, alpha: 1)
    public static let ocColorGray100 = UIColor(red: 0.176, green: 0.176, blue: 0.176, alpha: 1)
    public static let ocColorGray20 = UIColor(red: 0.886, green: 0.886, blue: 0.886, alpha: 1)
    public static let ocColorGray200 = UIColor(red: 0.133, green: 0.133, blue: 0.133, alpha: 1)
    public static let ocColorGray30 = UIColor(red: 0.831, green: 0.831, blue: 0.831, alpha: 1)
    public static let ocColorGray300 = UIColor(red: 0.086, green: 0.086, blue: 0.086, alpha: 1)
    public static let ocColorGray40 = UIColor(red: 0.776, green: 0.776, blue: 0.776, alpha: 1)
    public static let ocColorGray400 = UIColor(red: 0.043, green: 0.043, blue: 0.043, alpha: 1)
    public static let ocColorGray50 = UIColor(red: 0.663, green: 0.663, blue: 0.663, alpha: 1)
    public static let ocColorGray60 = UIColor(red: 0.553, green: 0.553, blue: 0.553, alpha: 1)
    public static let ocColorGray70 = UIColor(red: 0.439, green: 0.439, blue: 0.439, alpha: 1)
    public static let ocColorGray80 = UIColor(red: 0.353, green: 0.353, blue: 0.353, alpha: 1)
    public static let ocColorGray90 = UIColor(red: 0.263, green: 0.263, blue: 0.263, alpha: 1)
    public static let ocColorGreen100 = UIColor(red: 0.031, green: 0.486, blue: 0.263, alpha: 1)
    public static let ocColorGreen200 = UIColor(red: 0.031, green: 0.486, blue: 0.263, alpha: 1)
    public static let ocColorGreen300 = UIColor(red: 0.031, green: 0.486, blue: 0.263, alpha: 1)
    public static let ocColorGreen400 = UIColor(red: 0.031, green: 0.486, blue: 0.263, alpha: 1)
    public static let ocColorGreen500 = UIColor(red: 0.031, green: 0.486, blue: 0.263, alpha: 1)
    public static let ocColorGreen600 = UIColor(red: 0.031, green: 0.486, blue: 0.263, alpha: 1)
    public static let ocColorGreen700 = UIColor(red: 0.031, green: 0.486, blue: 0.263, alpha: 1)
    public static let ocColorGreen800 = UIColor(red: 0.031, green: 0.486, blue: 0.263, alpha: 1)
    public static let ocColorGreen900 = UIColor(red: 0.031, green: 0.486, blue: 0.263, alpha: 1)
    public static let ocColorInfoDark = UIColor(red: 0.000, green: 0.396, blue: 1.000, alpha: 1)
    public static let ocColorInfoDarker = UIColor(red: 0.000, green: 0.396, blue: 1.000, alpha: 1)
    public static let ocColorInfoDefault = UIColor(red: 0.000, green: 0.396, blue: 1.000, alpha: 1)
    public static let ocColorInfoLight = UIColor(red: 0.000, green: 0.396, blue: 1.000, alpha: 1)
    public static let ocColorInfoLighter = UIColor(red: 0.000, green: 0.396, blue: 1.000, alpha: 1)
    public static let ocColorInfoLightest = UIColor(red: 0.000, green: 0.396, blue: 1.000, alpha: 1)
    public static let ocColorNeutral10 = UIColor(red: 0.945, green: 0.945, blue: 0.945, alpha: 1)
    public static let ocColorNeutral100 = UIColor(red: 0.176, green: 0.176, blue: 0.176, alpha: 1)
    public static let ocColorNeutral20 = UIColor(red: 0.886, green: 0.886, blue: 0.886, alpha: 1)
    public static let ocColorNeutral200 = UIColor(red: 0.133, green: 0.133, blue: 0.133, alpha: 1)
    public static let ocColorNeutral30 = UIColor(red: 0.831, green: 0.831, blue: 0.831, alpha: 1)
    public static let ocColorNeutral300 = UIColor(red: 0.086, green: 0.086, blue: 0.086, alpha: 1)
    public static let ocColorNeutral40 = UIColor(red: 0.776, green: 0.776, blue: 0.776, alpha: 1)
    public static let ocColorNeutral400 = UIColor(red: 0.043, green: 0.043, blue: 0.043, alpha: 1)
    public static let ocColorNeutral50 = UIColor(red: 0.663, green: 0.663, blue: 0.663, alpha: 1)
    public static let ocColorNeutral60 = UIColor(red: 0.553, green: 0.553, blue: 0.553, alpha: 1)
    public static let ocColorNeutral70 = UIColor(red: 0.439, green: 0.439, blue: 0.439, alpha: 1)
    public static let ocColorNeutral80 = UIColor(red: 0.353, green: 0.353, blue: 0.353, alpha: 1)
    public static let ocColorNeutral90 = UIColor(red: 0.263, green: 0.263, blue: 0.263, alpha: 1)
    public static let ocColorNeutralBlack = UIColor(red: 0.067, green: 0.067, blue: 0.067, alpha: 1)
    public static let ocColorNeutralWhite = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1)
    public static let ocColorOrange100 = UIColor(red: 0.945, green: 0.498, blue: 0.161, alpha: 1)
    public static let ocColorOrange200 = UIColor(red: 0.945, green: 0.498, blue: 0.161, alpha: 1)
    public static let ocColorOrange300 = UIColor(red: 0.945, green: 0.498, blue: 0.161, alpha: 1)
    public static let ocColorOrange400 = UIColor(red: 0.945, green: 0.498, blue: 0.161, alpha: 1)
    public static let ocColorOrange500 = UIColor(red: 0.945, green: 0.498, blue: 0.161, alpha: 1)
    public static let ocColorOrange600 = UIColor(red: 0.945, green: 0.498, blue: 0.161, alpha: 1)
    public static let ocColorOrange700 = UIColor(red: 0.945, green: 0.498, blue: 0.161, alpha: 1)
    public static let ocColorOrange800 = UIColor(red: 0.945, green: 0.498, blue: 0.161, alpha: 1)
    public static let ocColorOrange900 = UIColor(red: 0.945, green: 0.498, blue: 0.161, alpha: 1)
    public static let ocColorPrimaryDark = UIColor(red: 0.031, green: 0.486, blue: 0.263, alpha: 1)
    public static let ocColorPrimaryDarker = UIColor(red: 0.031, green: 0.486, blue: 0.263, alpha: 1)
    public static let ocColorPrimaryDefault = UIColor(red: 0.031, green: 0.486, blue: 0.263, alpha: 1)
    public static let ocColorPrimaryLight = UIColor(red: 0.031, green: 0.486, blue: 0.263, alpha: 1)
    public static let ocColorPrimaryLighter = UIColor(red: 0.031, green: 0.486, blue: 0.263, alpha: 1)
    public static let ocColorPrimaryLightest = UIColor(red: 0.031, green: 0.486, blue: 0.263, alpha: 1)
    public static let ocColorRed100 = UIColor(red: 0.761, green: 0.129, blue: 0.059, alpha: 1)
    public static let ocColorRed200 = UIColor(red: 0.761, green: 0.129, blue: 0.059, alpha: 1)
    public static let ocColorRed300 = UIColor(red: 0.761, green: 0.129, blue: 0.059, alpha: 1)
    public static let ocColorRed400 = UIColor(red: 0.761, green: 0.129, blue: 0.059, alpha: 1)
    public static let ocColorRed500 = UIColor(red: 0.761, green: 0.129, blue: 0.059, alpha: 1)
    public static let ocColorRed600 = UIColor(red: 0.761, green: 0.129, blue: 0.059, alpha: 1)
    public static let ocColorRed700 = UIColor(red: 0.761, green: 0.129, blue: 0.059, alpha: 1)
    public static let ocColorRed800 = UIColor(red: 0.761, green: 0.129, blue: 0.059, alpha: 1)
    public static let ocColorRed900 = UIColor(red: 0.761, green: 0.129, blue: 0.059, alpha: 1)
    public static let ocColorSecondaryDark = UIColor(red: 0.945, green: 0.498, blue: 0.161, alpha: 1)
    public static let ocColorSecondaryDarker = UIColor(red: 0.945, green: 0.498, blue: 0.161, alpha: 1)
    public static let ocColorSecondaryDefault = UIColor(red: 0.945, green: 0.498, blue: 0.161, alpha: 1)
    public static let ocColorSecondaryLight = UIColor(red: 0.945, green: 0.498, blue: 0.161, alpha: 1)
    public static let ocColorSecondaryLighter = UIColor(red: 0.945, green: 0.498, blue: 0.161, alpha: 1)
    public static let ocColorSecondaryLightest = UIColor(red: 0.945, green: 0.498, blue: 0.161, alpha: 1)
    public static let ocColorSuccessDark = UIColor(red: 0.031, green: 0.486, blue: 0.263, alpha: 1)
    public static let ocColorSuccessDarker = UIColor(red: 0.031, green: 0.486, blue: 0.263, alpha: 1)
    public static let ocColorSuccessDefault = UIColor(red: 0.031, green: 0.486, blue: 0.263, alpha: 1)
    public static let ocColorSuccessLight = UIColor(red: 0.031, green: 0.486, blue: 0.263, alpha: 1)
    public static let ocColorSuccessLighter = UIColor(red: 0.031, green: 0.486, blue: 0.263, alpha: 1)
    public static let ocColorSuccessLightest = UIColor(red: 0.031, green: 0.486, blue: 0.263, alpha: 1)
    public static let ocColorTeal100 = UIColor(red: 0.133, green: 0.573, blue: 0.643, alpha: 1)
    public static let ocColorTeal200 = UIColor(red: 0.133, green: 0.573, blue: 0.643, alpha: 1)
    public static let ocColorTeal300 = UIColor(red: 0.133, green: 0.573, blue: 0.643, alpha: 1)
    public static let ocColorTeal400 = UIColor(red: 0.133, green: 0.573, blue: 0.643, alpha: 1)
    public static let ocColorTeal500 = UIColor(red: 0.133, green: 0.573, blue: 0.643, alpha: 1)
    public static let ocColorTeal600 = UIColor(red: 0.133, green: 0.573, blue: 0.643, alpha: 1)
    public static let ocColorTeal700 = UIColor(red: 0.133, green: 0.573, blue: 0.643, alpha: 1)
    public static let ocColorTeal800 = UIColor(red: 0.133, green: 0.573, blue: 0.643, alpha: 1)
    public static let ocColorTeal900 = UIColor(red: 0.133, green: 0.573, blue: 0.643, alpha: 1)
    public static let ocColorWarningDark = UIColor(red: 0.918, green: 0.690, blue: 0.063, alpha: 1)
    public static let ocColorWarningDarker = UIColor(red: 0.918, green: 0.690, blue: 0.063, alpha: 1)
    public static let ocColorWarningDefault = UIColor(red: 0.918, green: 0.690, blue: 0.063, alpha: 1)
    public static let ocColorWarningLight = UIColor(red: 0.918, green: 0.690, blue: 0.063, alpha: 1)
    public static let ocColorWarningLighter = UIColor(red: 0.918, green: 0.690, blue: 0.063, alpha: 1)
    public static let ocColorWarningLightest = UIColor(red: 0.918, green: 0.690, blue: 0.063, alpha: 1)
    public static let ocColorWhiteWhite = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1)
    public static let ocColorYellow100 = UIColor(red: 0.918, green: 0.690, blue: 0.063, alpha: 1)
    public static let ocColorYellow200 = UIColor(red: 0.918, green: 0.690, blue: 0.063, alpha: 1)
    public static let ocColorYellow300 = UIColor(red: 0.918, green: 0.690, blue: 0.063, alpha: 1)
    public static let ocColorYellow400 = UIColor(red: 0.918, green: 0.690, blue: 0.063, alpha: 1)
    public static let ocColorYellow500 = UIColor(red: 0.918, green: 0.690, blue: 0.063, alpha: 1)
    public static let ocColorYellow600 = UIColor(red: 0.918, green: 0.690, blue: 0.063, alpha: 1)
    public static let ocColorYellow700 = UIColor(red: 0.918, green: 0.690, blue: 0.063, alpha: 1)
    public static let ocColorYellow800 = UIColor(red: 0.918, green: 0.690, blue: 0.063, alpha: 1)
    public static let ocColorYellow900 = UIColor(red: 0.918, green: 0.690, blue: 0.063, alpha: 1)
    public static let ocFontFamilyInter = Inter
    public static let ocFontSize10 = 10
    public static let ocFontSize12 = 12
    public static let ocFontSize14 = 14
    public static let ocFontSize16 = 16
    public static let ocFontSize18 = 18
    public static let ocFontSize20 = 20
    public static let ocFontSize22 = 22
    public static let ocFontSize24 = 24
    public static let ocFontSize28 = 28
    public static let ocFontSize32 = 32
    public static let ocFontSize40 = 40
    public static let ocFontSize48 = 48
    public static let ocFontSize60 = 60
    public static let ocFontSize76 = 76
    public static let ocFontSize92 = 92
    public static let ocFontWeight100 = Thin
    public static let ocFontWeight200 = Extra Light
    public static let ocFontWeight300 = Light
    public static let ocFontWeight400 = Regular
    public static let ocFontWeight500 = Medium
    public static let ocFontWeight600 = Semi Bold
    public static let ocFontWeight700 = Bold
    public static let ocFontWeight800 = Extra Bold
    public static let ocFontWeight900 = Black
    public static let ocIconError = UIColor(red: 0.761, green: 0.129, blue: 0.059, alpha: 1)
    public static let ocIconInformation = UIColor(red: 0.000, green: 0.396, blue: 1.000, alpha: 1)
    public static let ocIconPrimary = UIColor(red: 0.031, green: 0.486, blue: 0.263, alpha: 1)
    public static let ocIconSuccess = UIColor(red: 0.031, green: 0.486, blue: 0.263, alpha: 1)
    public static let ocIconWarning = UIColor(red: 0.918, green: 0.690, blue: 0.063, alpha: 1)
    public static let ocLayoutBorderNone = [object Object]
    public static let ocLayoutBorderPrimaryDashed05 = [object Object]
    public static let ocLayoutBorderPrimaryDashed1 = [object Object]
    public static let ocLayoutBorderPrimaryDashed2 = [object Object]
    public static let ocLayoutBorderPrimaryDashed3 = [object Object]
    public static let ocLayoutBorderPrimaryDashed4 = [object Object]
    public static let ocLayoutBorderPrimaryDashed5 = [object Object]
    public static let ocLayoutBorderPrimarySolid05 = [object Object]
    public static let ocLayoutBorderPrimarySolid1 = [object Object]
    public static let ocLayoutBorderPrimarySolid2 = [object Object]
    public static let ocLayoutBorderPrimarySolid3 = [object Object]
    public static let ocLayoutBorderPrimarySolid4 = [object Object]
    public static let ocLayoutBorderPrimarySolid5 = [object Object]
    public static let ocLayoutBorderSecondaryDashed05 = [object Object]
    public static let ocLayoutBorderSecondaryDashed1 = [object Object]
    public static let ocLayoutBorderSecondaryDashed2 = [object Object]
    public static let ocLayoutBorderSecondaryDashed3 = [object Object]
    public static let ocLayoutBorderSecondaryDashed4 = [object Object]
    public static let ocLayoutBorderSecondaryDashed5 = [object Object]
    public static let ocLayoutBorderSecondarySolid05 = [object Object]
    public static let ocLayoutBorderSecondarySolid1 = [object Object]
    public static let ocLayoutBorderSecondarySolid2 = [object Object]
    public static let ocLayoutBorderSecondarySolid3 = [object Object]
    public static let ocLayoutBorderSecondarySolid4 = [object Object]
    public static let ocLayoutBorderSecondarySolid5 = [object Object]
    public static let ocLayoutRadius16 = 16
    public static let ocLayoutRadius2 = 2
    public static let ocLayoutRadius24 = 24
    public static let ocLayoutRadius4 = 4
    public static let ocLayoutRadius8 = 8
    public static let ocLayoutRadiusNone = 0
    public static let ocLayoutRadiusRounded = 50
    public static let ocLayoutShadowPrimaryMdLeft = [object Object]
    public static let ocLayoutShadowPrimaryMdMid = [object Object]
    public static let ocLayoutShadowPrimaryMdRight = [object Object]
    public static let ocLayoutShadowPrimaryXsLeft = [object Object]
    public static let ocLayoutShadowPrimaryXsMid = [object Object]
    public static let ocLayoutShadowPrimaryXsRight = [object Object]
    public static let ocLayoutShadowPrimaryXxsLeft = [object Object]
    public static let ocLayoutShadowPrimaryXxsMid = [object Object]
    public static let ocLayoutShadowPrimaryXxsRight = [object Object]
    public static let ocLayoutShadowPrimaryXxxsLeft = [object Object]
    public static let ocLayoutShadowPrimaryXxxsMid = [object Object]
    public static let ocLayoutShadowPrimaryXxxsRight = [object Object]
    public static let ocLayoutSpacingExtended1 = 8*7
    public static let ocLayoutSpacingExtended2 = 8*8
    public static let ocLayoutSpacingLg = 8*3
    public static let ocLayoutSpacingMd = 4*4
    public static let ocLayoutSpacingSm = 4*3
    public static let ocLayoutSpacingXl = 8*4
    public static let ocLayoutSpacingXs = 4*2
    public static let ocLayoutSpacingXxl = 8*5
    public static let ocLayoutSpacingXxs = 4*1
    public static let ocLayoutSpacingXxxl = 8*6
    public static let ocLayoutSpacingXxxs = 4/2
    public static let ocLetterSpacing0 = 0%
    public static let ocLetterSpacing1 = 1%
    public static let ocLetterSpacing2 = -2.5%
    public static let ocLetterSpacing3 = -2%
    public static let ocLetterSpacing4 = 2%
    public static let ocLineHeight110 = 110%
    public static let ocLineHeight130 = 130%
    public static let ocLineHeight140 = 140%
    public static let ocLineHeight150 = 150%
    public static let ocMobileBodyBold = [object Object]
    public static let ocMobileBodyExtraLight = [object Object]
    public static let ocMobileBodyLgBold = [object Object]
    public static let ocMobileBodyLgExtraLight = [object Object]
    public static let ocMobileBodyLgLight = [object Object]
    public static let ocMobileBodyLgMedium = [object Object]
    public static let ocMobileBodyLgRegular = [object Object]
    public static let ocMobileBodyLgSemiBold = [object Object]
    public static let ocMobileBodyLight = [object Object]
    public static let ocMobileBodyMedium = [object Object]
    public static let ocMobileBodyRegular = [object Object]
    public static let ocMobileBodySemiBold = [object Object]
    public static let ocMobileHeading6Bold = [object Object]
    public static let ocMobileHeading6ExtraLight = [object Object]
    public static let ocMobileHeading6Light = [object Object]
    public static let ocMobileHeading6Medium = [object Object]
    public static let ocMobileHeading6Regular = [object Object]
    public static let ocMobileHeading6SemiBold = [object Object]
    public static let ocMobileLabelBold = [object Object]
    public static let ocMobileLabelExtraLight = [object Object]
    public static let ocMobileLabelLight = [object Object]
    public static let ocMobileLabelMedium = [object Object]
    public static let ocMobileLabelRegular = [object Object]
    public static let ocMobileLabelSemiBold = [object Object]
    public static let ocMobileLabelUpperBold = [object Object]
    public static let ocMobileLabelUpperExtraLight = [object Object]
    public static let ocMobileLabelUpperLight = [object Object]
    public static let ocMobileLabelUpperMedium = [object Object]
    public static let ocMobileLabelUpperRegular = [object Object]
    public static let ocMobileLabelUpperSemiBold = [object Object]
    public static let ocMobileSmallBold = [object Object]
    public static let ocMobileSmallExtraLight = [object Object]
    public static let ocMobileSmallLight = [object Object]
    public static let ocMobileSmallMedium = [object Object]
    public static let ocMobileSmallRegular = [object Object]
    public static let ocMobileSmallSemiBold = [object Object]
    public static let ocMobileSmallUpperBold = [object Object]
    public static let ocMobileSmallUpperExtraLight = [object Object]
    public static let ocMobileSmallUpperLight = [object Object]
    public static let ocMobileSmallUpperMedium = [object Object]
    public static let ocMobileSmallUpperRegular = [object Object]
    public static let ocMobileSmallUpperSemiBold = [object Object]
    public static let ocOpacity100 = 100%
    public static let ocOpacity25 = 25%
    public static let ocOpacity50 = 50%
    public static let ocOpacity75 = 75%
    public static let ocOpacityNone = none
    public static let ocParagaphSpacing12 = 12
    public static let ocParagaphSpacing16 = 16
    public static let ocParagaphSpacing4 = 4
    public static let ocParagaphSpacing8 = 8
    public static let ocRadius0 = 0
    public static let ocRadius16 = 16
    public static let ocRadius2 = 2
    public static let ocRadius24 = 24
    public static let ocRadius32 = 32
    public static let ocRadius4 = 4
    public static let ocRadius50 = 50
    public static let ocRadius8 = 8
    public static let ocSizing12 = 4*3
    public static let ocSizing16 = 4*4
    public static let ocSizing2 = 2*1
    public static let ocSizing20 = 4*5
    public static let ocSizing24 = 4*6
    public static let ocSizing28 = 4*7
    public static let ocSizing32 = 4*8
    public static let ocSizing36 = 4*9
    public static let ocSizing4 = 4*1
    public static let ocSizing40 = 4*10
    public static let ocSizing44 = 4*11
    public static let ocSizing48 = 4*12
    public static let ocSizing52 = 4*13
    public static let ocSizing56 = 4*14
    public static let ocSizing60 = 4*15
    public static let ocSizing64 = 64
    public static let ocSizing8 = 4*2
    public static let ocSurfaceAction = UIColor(red: 0.031, green: 0.486, blue: 0.263, alpha: 1)
    public static let ocSurfaceActionHover = UIColor(red: 0.031, green: 0.486, blue: 0.263, alpha: 1)
    public static let ocSurfaceDisabled = UIColor(red: 0.776, green: 0.776, blue: 0.776, alpha: 1)
    public static let ocSurfaceError = UIColor(red: 0.761, green: 0.129, blue: 0.059, alpha: 1)
    public static let ocSurfaceHighlight = UIColor(red: 0.133, green: 0.573, blue: 0.643, alpha: 1)
    public static let ocSurfaceInformation = UIColor(red: 0.000, green: 0.396, blue: 1.000, alpha: 1)
    public static let ocSurfacePage = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1)
    public static let ocSurfacePrimary = UIColor(red: 0.945, green: 0.945, blue: 0.945, alpha: 1)
    public static let ocSurfaceSecondary = UIColor(red: 0.945, green: 0.945, blue: 0.945, alpha: 1)
    public static let ocSurfaceSuccess = UIColor(red: 0.031, green: 0.486, blue: 0.263, alpha: 1)
    public static let ocSurfaceWarning = UIColor(red: 0.918, green: 0.690, blue: 0.063, alpha: 1)
    public static let ocTextAction = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1)
    public static let ocTextActionHover = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1)
    public static let ocTextBody = UIColor(red: 0.067, green: 0.067, blue: 0.067, alpha: 1)
    public static let ocTextCaseCapitalize = capitalize
    public static let ocTextCaseLowercase = lowercase
    public static let ocTextCaseNone = none
    public static let ocTextCaseUppercase = uppercase
    public static let ocTextDecorationLineThrough = line-through
    public static let ocTextDecorationNone = none
    public static let ocTextDecorationUnderline = underline
    public static let ocTextDisabled = UIColor(red: 0.176, green: 0.176, blue: 0.176, alpha: 1)
    public static let ocTextError = UIColor(red: 0.761, green: 0.129, blue: 0.059, alpha: 1)
    public static let ocTextHeading = UIColor(red: 0.067, green: 0.067, blue: 0.067, alpha: 1)
    public static let ocTextHighlight = UIColor(red: 0.133, green: 0.573, blue: 0.643, alpha: 1)
    public static let ocTextInformation = UIColor(red: 0.000, green: 0.396, blue: 1.000, alpha: 1)
    public static let ocTextOnAction = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1)
    public static let ocTextOnDisabled = UIColor(red: 0.043, green: 0.043, blue: 0.043, alpha: 1)
    public static let ocTextSuccess = UIColor(red: 0.031, green: 0.486, blue: 0.263, alpha: 1)
    public static let ocTextWarning = UIColor(red: 0.918, green: 0.690, blue: 0.063, alpha: 1)
    public static let ocWebBodyBold = [object Object]
    public static let ocWebBodyExtraLight = [object Object]
    public static let ocWebBodyLight = [object Object]
    public static let ocWebBodyMedium = [object Object]
    public static let ocWebBodyRegular = [object Object]
    public static let ocWebBodySemiBold = [object Object]
    public static let ocWebBodySmallBold = [object Object]
    public static let ocWebBodySmallExtraLight = [object Object]
    public static let ocWebBodySmallLight = [object Object]
    public static let ocWebBodySmallMedium = [object Object]
    public static let ocWebBodySmallRegular = [object Object]
    public static let ocWebBodySmallSemiBold = [object Object]
    public static let ocWebHeading1Bold = [object Object]
    public static let ocWebHeading1ExtraLight = [object Object]
    public static let ocWebHeading1Light = [object Object]
    public static let ocWebHeading1Medium = [object Object]
    public static let ocWebHeading1Regular = [object Object]
    public static let ocWebHeading1SemiBold = [object Object]
    public static let ocWebHeading2Bold = [object Object]
    public static let ocWebHeading2ExtraLight = [object Object]
    public static let ocWebHeading2Light = [object Object]
    public static let ocWebHeading2Medium = [object Object]
    public static let ocWebHeading2Regular = [object Object]
    public static let ocWebHeading2SemiBold = [object Object]
    public static let ocWebHeading3Bold = [object Object]
    public static let ocWebHeading3ExtraLight = [object Object]
    public static let ocWebHeading3Light = [object Object]
    public static let ocWebHeading3Medium = [object Object]
    public static let ocWebHeading3Regular = [object Object]
    public static let ocWebHeading3SemiBold = [object Object]
    public static let ocWebHeading4Bold = [object Object]
    public static let ocWebHeading4ExtraLight = [object Object]
    public static let ocWebHeading4Light = [object Object]
    public static let ocWebHeading4Medium = [object Object]
    public static let ocWebHeading4Regular = [object Object]
    public static let ocWebHeading4SemiBold = [object Object]
    public static let ocWebHeading5Bold = [object Object]
    public static let ocWebHeading5ExtraLight = [object Object]
    public static let ocWebHeading5Light = [object Object]
    public static let ocWebHeading5Medium = [object Object]
    public static let ocWebHeading5Regular = [object Object]
    public static let ocWebHeading5SemiBold = [object Object]
    public static let ocWebHeading6Bold = [object Object]
    public static let ocWebHeading6ExtraLight = [object Object]
    public static let ocWebHeading6Light = [object Object]
    public static let ocWebHeading6Medium = [object Object]
    public static let ocWebHeading6Regular = [object Object]
    public static let ocWebHeading6SemiBold = [object Object]
    public static let ocWebLabelBold = [object Object]
    public static let ocWebLabelExtraLight = [object Object]
    public static let ocWebLabelLight = [object Object]
    public static let ocWebLabelMedium = [object Object]
    public static let ocWebLabelRegular = [object Object]
    public static let ocWebLabelSemiBold = [object Object]
    public static let ocWebSmallBold = [object Object]
    public static let ocWebSmallExtraLight = [object Object]
    public static let ocWebSmallLight = [object Object]
    public static let ocWebSmallMedium = [object Object]
    public static let ocWebSmallRegular = [object Object]
    public static let ocWebSmallSemiBold = [object Object]
}
